import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { TimeProvider } from '../contexts/Time'
import Status from '../components/Status'
import Header from '../components/Header'
import Footer from '../components/Footer'
import Title from '../components/Title'
import clsx from 'clsx'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <TimeProvider>
        <Title />
        <body className={clsx(inter.className, "flex flex-col min-h-screen")}>
          <Status />
          <Header />
          {children}
          <Footer />
        </body>
      </TimeProvider>
    </html>
  )
}
